wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: LSTMAttentionWithTemperature
dataset:
  desc: null
  value: Helheim, Aletsch, jakobshavn
epochs:
  desc: null
  value: 50
_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1729722107
    t:
      1:
      - 1
      - 54
      - 55
      2:
      - 1
      - 54
      - 55
      3:
      - 16
      - 23
      4: 3.11.0
      5: 0.17.8
      8:
      - 3
      - 5
      13: windows-amd64
